[package]
name = "maze_of_ferris"
version = "0.1.0"
edition = "2021"

# TODO
[dependencies]
bevy = "0.9.0"


[workspace]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"

[profile.dev.package."*"]
opt-level = 3