[package]
name = "rubiks_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.40.0"
derive_more = "0.99.16"
lazy_static = "1.4.0"
glam = "0.22.0"
rustc-hash = "1.1.0"